server:
  port: 8193
  context-path: /

# 服务节点,要求分布式下每个节点不同
##node: 01

spring:
  dubbo:
    application:
      name: xxpay-manage
    consumer:
      timeout: 1200000
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: org.xxpay.manage
  redis:
    host: 127.0.0.1
    password: root
    port: 6379
    database: 0
    timeout: 1000
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      number_format: 0.##
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 10Mb
  jackson:
    serialization:
      INDENT_OUTPUT: true
  profiles:
     active:

# JWT
jwt:
  cookie: XxPay_Mgr_Token
  secret: XxpPayGood
  expiration: 86400 # 1天
  mchSecret: XxpPayGood

logging:
  file: /home/xxpay_0514/log/xxpay-manage.log
  level:
    root: info

config:
  mchQrUrl: http://127.0.0.1:8191/payment/qrcode
  downMchBillUrl: http://localhost:8195/mch_bill_down
  loginMchUrl: http://127.0.0.1:8191/x_mch/start/index.html#/user/mgr_login/mchId=%s/token=%s
  loginAgentUrl: http://127.0.0.1:8192/x_agent/start/index.html#/user/mgr_login/agentId=%s/token=%s
  settNotifyUrl: http://mgr.hanxincorp.com/api/notify/sett
  payUrl: http://pay.hanxincorp.com/api

oos:
  endpoint: oss-cn-hongkong.aliyuncs.com
  accessKeyId: LTAI4G2R1oxaVzAQ9JTT9Zf3
  accessKeySecret: gCHa7PDibyybb3rZRlU1yzTDtF7CO7
  bucketName: test-hxconfiguration1