server:
  port: 3020

# 服务节点,要求分布式下每个节点不同
##node: 01

spring:
  dubbo:
    application:
      name: xxpay-pay
    consumer:
      timeout: 5200000
    registry:
      address: @zookeeper.url@
    protocol:
      name: dubbo
      port: 20881
    scan: org.xxpay.pay
  redis:
    host: @redis.ip@
    password: @redis.pass@
    port: @redis.port@
    database: 0
    timeout: 1000
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  activemq:
    broker-url: @activemq.url@
    in-memory: false
    pool:
     enabled: true
     max-connections: 10
     idle-timeout: 30000  # 空闲的连接过期时间，默认为30秒
     expiry-timeout: 0 # 强制的连接过期时间，与idleTimeout的区别在于：idleTimeout是在连接空闲一段时间失效，而expiryTimeout不管当前连接的情况，只要达到指定时间就失效。默认为0，never
#    user: @activemq.user@
#    password: @activemq.password@
  freemarker:

    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      number_format: 0.##

logging:
  file: /home/xxpay_0514/log/xxpay-pay.log
  level:
    root: info

config:
  notifyUrl: @pay.site.url@/notify/%s/notify_res.htm
  returnUrl: @pay.site.url@/notify/%s/return_res.htm
  notifyTransUrl: @pay.site.url@/notify/%s/trans_notify.htm
  notifyDivisionUrl: @pay.site.url@/notify/%s/division_notify.htm
  payUrl: @pay.site.url@/api
  certRootPath: @cert.root.path@
  agentpayNotifyUrl: @pay.site.url@/api/agentpay/notify

task:
  reissue.pay.switch: @task.reissue.pay.switch@
  reissue.pay.ip: @task.reissue.pay.ip@
  reissue.trans.switch: @task.reissue.trans.switch@
  reissue.trans.ip: @task.reissue.trans.ip@
  reissue.agentpay.switch: @task.reissue.agentpay.switch@
  reissue.agentpay.ip: @task.reissue.agentpay.ip@


rocketmq:
  accessKey: @rocketmq.accessKey@
  secretKey: @rocketmq.secretKey@
  nameSrvAddr: @rocketmq.nameSrvAddr@
  topic: @rocketmq.topic@
  groupId: @rocketmq.groupId@
  tag: @rocketmq.tag@
  orderTopic: @rocketmq.orderTopic@
  orderGroupId: @rocketmq.orderGroupId@
  orderTag: @rocketmq.orderTag@