server:
  port: 8192
  context-path: /

# 服务节点,要求分布式下每个节点不同
## node: 01

spring:
  dubbo:
    application:
      name: xxpay-agent
    consumer:
      timeout: 1200000
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: org.xxpay.agent
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      number_format: 0.##

  jackson:
    serialization:
      INDENT_OUTPUT: true
  profiles:
     active: prod

# JWT
jwt:
  cookie: XxPay_Agent_Token
  secret: XxpPayGood
  expiration: 86400 # 1天

logging:
  file: /home/xxpay_0514/log/xxpay-agent.log
  level:
    root: info

config:
  payUrl: http://pay.hanxincorp.com/api


oos:
  endpoint: oss-cn-hongkong.aliyuncs.com
  accessKeyId: LTAI4G2R1oxaVzAQ9JTT9Zf3
  accessKeySecret: gCHa7PDibyybb3rZRlU1yzTDtF7CO7
  bucketName: test-hxconfiguration1